## The dataset is compiled from the 1994 Census database and contains income data.
### Data Information:
* age: continuous.
* workclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
* fnlwgt: continuous.
* education: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, * Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
* education-num: continuous.
* marital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
* occupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
* relationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
* race: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
* sex: Female, Male.
* capital-gain: continuous.
* capital-loss: continuous.
* hours-per-week: continuous.
* native-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.
* salary: >50K,<=50K

## Perform data analysis using Pandas by completing the given tasks.
####

In [ ]:
import pandas as pd

In [36]:
# loading the dataset
data = pd.read_csv("/Users/lena/Desktop/Python-Tasks/adult.data.csv")
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

**1. Calculate how many men and women (attribute *sex*) are represented in this dataset.**

In [ ]:
men = (data['sex'] == 'Male').sum()
women = (data['sex'] == 'Female').sum()

print("Men:", men)
print("Women:", women)

Men: 21790
Women: 10771

In [37]:
print(data['sex'].value_counts())

sex
Male      21790
Female    10771
Name: count, dtype: int64

**2. What is the average age of men (attribute *age*) across the entire dataset?**

In [27]:
avg_male_age = data[data['sex'] == 'Male']['age'].mean()
print(f'Average age of men: {avg_male_age}')

Average age of men: 39.43354749885268

**3. What is the proportion of United States citizens (*native-country* attribute)?**

In [80]:
US_citizen_proportion = len(data[data['native-country'] == 'United-States'])*100/len(data)
print('The proportion of United States citizens:',US_citizen_proportion)

The proportion of United States citizens: 89.5857006848684

**4-5. Calculate the mean and standard deviation of the age of those who earn more than 50K per year (the *salary* attribute) and those who earn less than 50K per year**

In [104]:
mean_less = data[data['salary'] == '<=50K']['age'].mean()
mean_more = data[data['salary'] == '>50K']['age'].mean()

std_less = data[data['salary'] == '<=50K']['age'].std()
std_more = data[data['salary'] == '>50K']['age'].std()

print(f'\nMean of the age of those who earn less than 50K per year: {mean_less}, std: {std_less}\nMean of the age of those who earn more than 50K per year: {mean_more}, std: {std_more}')

Mean of the age of those who earn less than 50K per year: 36.78373786407767, std: 14.02008849082488
Mean of the age of those who earn more than 50K per year: 44.24984058155847, std: 10.519027719851826

**6. Is it true that people who earn more than 50k have at least a higher education? (*education indicator – Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters or Doctorate*)**

In [24]:
higher_education = [
    'Bachelors',
    'Prof-school',
    'Assoc-acdm',
    'Assoc-voc',
    'Masters',
    'Doctorate'
]
result = data[data['salary'] == '>50K']['education'].isin(higher_education).all()

print(result)

False

**7. Find age statistics for each race (*race* attribute) and each gender. Use *groupby* and *describe*. Find the maximum age of males of the *Asian-Pac-Islander* race.**

In [105]:
result = data.groupby(['race', 'sex'])['age'].max()
print(f"Max age of the Asian-Pac-Islander Male: {result['Asian-Pac-Islander', 'Male']}")

Max age of the Asian-Pac-Islander Male: 90

**8. Among whom is the proportion of high-earning individuals (>50K) higher: married or single men (*marital-status* indicator)? We consider those whose *marital-status* begins with *Married* (Married-civ-spouse, Married-spouse-absent, or Married-AF-spouse) to be married; the rest are considered single.**

In [46]:
married = data[data['marital-status'].str.startswith('Married')]
single = data[~data['marital-status'].str.startswith('Married')]

married_percentage = len(married[married['salary']=='>50K'])*100/len(data[data['salary']=='>50K'])
single_percentage = len(single[single['salary']=='>50K'])*100/len(data[data['salary']=='>50K'])

print('Married percentage: ',married_percentage,'%')
print('Single percentage: ',single_percentage,'%')

Married percentage:  85.9074097691621 %
Single percentage:  14.092590230837903 %

**9. What is the maximum number of hours a person works per week (hours-per-week indicator)? How many people work that many hours, and what percentage of them earn a lot?**

In [58]:
max_hours = data['hours-per-week'].max()

hard_workers = data[data['hours-per-week'] == max_hours]

rich_hard_workers=(hard_workers['salary']=='>50K').sum()*100/len(hard_workers)


print(f'Max hours per week: {max_hours}')
print(f'People working max hours: {len(hard_workers)}')
print(f'Percentage earning >50K: {rich_hard_workers:.1f}%')

Max hours per week: 99
People working max hours: 85
Percentage earning >50K: 29.4%

**10. Calculate the average working hours (*hours-per-week*) of low and high earners (*salary*) for each country (*native-country*).**

In [ ]:
avg_work_hours_per_cntr = (data.groupby(['native-country', 'salary'])['hours-per-week'].mean().round(1).reset_index())
print(avg_work_hours_per_cntr)

   native-country salary  hours-per-week
0               ?  <=50K            40.2
1               ?   >50K            45.5
2        Cambodia  <=50K            41.4
3        Cambodia   >50K            40.0
4          Canada  <=50K            37.9
..            ...    ...             ...
77  United-States   >50K            45.5
78        Vietnam  <=50K            37.2
79        Vietnam   >50K            39.2
80     Yugoslavia  <=50K            41.6
81     Yugoslavia   >50K            49.5

[82 rows x 3 columns]

**11.Group people into age groups *young*, *adult*, *retiree*, where:**
* *young* corresponds to 16-35 years old
* *adult* - 35-70 years old
* *retiree* - 70-100 years old

**Enter the name of the appropriate age group for each person in the new AgeGroup column.**

In [78]:
data['AgeGroup'] = pd.cut(
    data['age'],
    bins=[16, 35, 70, 100],
    labels=['young', 'adult', 'retiree']
)

data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary,AgeGroup
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K,adult
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,adult
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,adult
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,adult
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K,young

**12-13. Determine the number of people earning >50K in each age group (AgeGroup column), and also output the name of the age group in which people most often earn more than 50K (>50K)**

In [89]:
groups = data[data['salary'] == '>50K'].groupby('AgeGroup')['salary'].count()
print(groups)

print(f'Age group with most >50K earners: {groups.idxmax()}')

AgeGroup
young      1705
adult      6042
retiree      94
Name: salary, dtype: int64
Age group with most >50K earners: adult

/var/folders/fn/8rgh2lns0llfdtqsr_46wttc0000gn/T/ipykernel_30281/299392453.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  groups = data[data['salary'] == '>50K'].groupby('AgeGroup')['salary'].count()

**14. Group people by employment type (the occupation column) and determine the number of people in each group. Then write a filter function, filter_func, that will return only those groups in which the average age (the age column) is 40 or less and in which all employees work more than 5 hours per week (the hours-per-week column).**

In [ ]:
occupation_count = data.groupby('occupation')['occupation'].count()
print(occupation_count)

def filter_func(group):
    cond1 = group['age'].mean() <= 40
    cond2 = (group['hours-per-week'] > 5).all()
    return cond1 and cond2

filtered = data.groupby('occupation').filter(filter_func)
print(filtered)

occupation
?                    1843
Adm-clerical         3770
Armed-Forces            9
Craft-repair         4099
Exec-managerial      4066
Farming-fishing       994
Handlers-cleaners    1370
Machine-op-inspct    2002
Other-service        3295
Priv-house-serv       149
Prof-specialty       4140
Protective-serv       649
Sales                3650
Tech-support          928
Transport-moving     1597
Name: occupation, dtype: int64
       age    workclass  fnlwgt     education  education-num  \
442     24  Federal-gov  191073       HS-grad              9
1300    29  Federal-gov  301010  Some-college             10
14613   39  Federal-gov  227597       HS-grad              9
16111   24  Federal-gov  287988     Bachelors             13
18034   34  Federal-gov  172716          12th              8
18644   23  Federal-gov  163870  Some-college             10
18769   30  Federal-gov   76313       HS-grad              9
25799   46  Federal-gov  344415       Masters             14
32316   23  Federal-gov  173851       HS-grad              9

           marital-status    occupation    relationship                race  \
442         Never-married  Armed-Forces       Own-child               White
1300        Never-married  Armed-Forces   Not-in-family               Black
14613       Never-married  Armed-Forces   Not-in-family               White
16111       Never-married  Armed-Forces   Not-in-family               White
18034  Married-civ-spouse  Armed-Forces         Husband               White
18644       Never-married  Armed-Forces  Other-relative               White
18769  Married-civ-spouse  Armed-Forces  Other-relative  Amer-Indian-Eskimo
25799  Married-civ-spouse  Armed-Forces         Husband               White
32316       Never-married  Armed-Forces   Not-in-family               White

        sex  capital-gain  capital-loss  hours-per-week native-country salary  \
442    Male             0             0              40  United-States  <=50K
1300   Male             0             0              60  United-States  <=50K
14613  Male             0             0              50  United-States  <=50K
16111  Male             0             0              40  United-States  <=50K
18034  Male             0             0              40  United-States  <=50K
18644  Male             0             0              40  United-States  <=50K
18769  Male             0             0              48  United-States  <=50K
25799  Male             0          1887              40  United-States   >50K
32316  Male             0             0               8  United-States  <=50K

      AgeGroup
442      young
1300     young
14613    adult
16111    young
18034    young
18644    young
18769    young
25799    adult
32316    young

occupation
Armed-Forces    9
dtype: int64